config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # ホーム画面(最初にアクセスしたときのビューの指定)
  root 'home#index'                                                                         # ホーム画面

  # はじめての方へ #
  get '/beginner',                                  to: 'beginner#index'                    # 鍼灸治療とは
  get '/beginner/visit',                            to: 'beginner#visit'                    # ご来院にあたって
  get '/beginner/self-introduction',                to: 'beginner#self-introduction'        # 施術者紹介

  # 施術の流れ #
  get '/procedure_flow',                            to: 'procedure_flow#index'              # 施術の流れ

  # 治療方針 #
  get '/treatment_policy',                          to: 'treatment_policy#index'            # 治療方針
  get '/treatment_policy/faq',                      to: 'treatment_policy#faq'              # こんな症状にお悩みなら
  get '/treatment_policy/lifestyle',                to: 'treatment_policy#lifestyle'        # ライフスタイルに合わせた治療方針
  get '/treatment_policy/reverberation',            to: 'treatment_policy#reverberation'    # 痛い鍼はヘタなのか

  # お問い合わせ #
  get   '/contact',                                 to: 'contact#index'                     # お問い合わせ
  get   '/contact/confirm',                         to: 'contact#index'                     # お問い合わせ
  post  '/contact/confirm',                         to: 'contact#confirm'                   # 確認画面
  get   '/contact/thanks',                          to: 'home#index'                        # ホーム画面
  post  '/contact/thanks',                          to: 'contact#thanks'                    # 送信完了

  # ログイン系 #
  get     '/login',                                 to: 'sessions#new'
  post    '/login',                                 to: 'sessions#create'
  delete  '/logout',                                to: 'sessions#destroy'

  # その他 #
  get '/other/calender',                            to: 'other#calender'                    # カレンダー一覧

  # 管理者用 #
  get     '/tasks',                                 to: 'tasks#index'                       # 管理者ページログイン画面
  get     '/tasks/logged_in',                       to: 'tasks#_logged_in'                  # ログイン成功(設定画面へ)
  get     '/tasks/not_logged_in',                   to: 'tasks#_not_logged_in'              # ログイン失敗(ログイン画面へ)
  get     '/tasks/regular_holiday_setting',         to: 'tasks#regular_holiday_setting'     # 定休日設定
  post    '/tasks/regular_holiday_setting',         to: 'tasks#set_regular_holiday'         # 定休日設定(データ登録処理)
  get     '/tasks/specific_holiday_setting',        to: 'tasks#specific_holiday_setting'    # 特別休日設定
  post    '/tasks/specific_holiday_setting',        to: 'tasks#set_holiday'                 # 特別休日設定(データ登録処理)
  delete  '/tasks/specific_holiday_setting',        to: 'tasks#destroy_calender_holiday'    # 特別休日設定(データ消去処理)
  get     '/tasks/information_setting',             to: 'tasks#information_setting'         # INFORMATION設定
  post    '/tasks/information_setting',             to: 'tasks#set_information'             # INFORMATION設定(データ登録処理)
  delete  '/tasks/information_setting',             to: 'tasks#destroy_information'         # INFORMATION設定(データ消去処理)

  # 404/500系エラー対応 #
  # ★★★これは一番下に設定しないとおかしなことになるよ！！★★★
  #get '*not_found' => 'application#routing_error'
  #post '*not_found' => 'application#routing_error'
  # ★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :login_check

  def index
  end

  def _logged_in
  end

  def _not_logged_in
  end

  #####################################
  # 定休日設定
  #####################################
  def regular_holiday_setting
    @calenderHolidaySchedule = CalenderWeekDay.first
  end

  #####################################
  # 特別休日設定
  #####################################
  def specific_holiday_setting
    t = Time.new
    # 今月以降の特別休日を取得する
    @calenderHolidays = CalenderHoliday.where(date_holiday: t.beginning_of_month..Float::INFINITY).order(date_holiday: :desc)
  end

  #####################################
  # INFORMATION設定
  #####################################
  def information_setting
    @informationSetting = InformationSetting.all.order(date_information: :desc)
  end

  #####################################
  # 定休日登録処理
  #####################################
  def set_regular_holiday
    # 定休日を取得
    holiday_Mon = params[:session][:am_Mon].to_i + params[:session][:pm_Mon].to_i
    holiday_Tue = params[:session][:am_Tue].to_i + params[:session][:pm_Tue].to_i
    holiday_Wed = params[:session][:am_Wed].to_i + params[:session][:pm_Wed].to_i
    holiday_Thu = params[:session][:am_Thu].to_i + params[:session][:pm_Thu].to_i
    holiday_Fri = params[:session][:am_Fri].to_i + params[:session][:pm_Fri].to_i
    holiday_Sat = params[:session][:am_Sat].to_i + params[:session][:pm_Sat].to_i
    holiday_Sun = params[:session][:am_Sun].to_i + params[:session][:pm_Sun].to_i

    # 定休日テーブルを取得
    calenderRegularHoliday = CalenderWeekDay.first

    # データアップデート
    calenderRegularHoliday.update(\
      monday: holiday_Mon\
      , tuesday: holiday_Tue\
      , wednesday: holiday_Wed\
      , thursday: holiday_Thu\
      , friday: holiday_Fri\
      , saturday: holiday_Sat\
      , sunday: holiday_Sun\
    )

    # ホームに戻る
    redirect_to root_path
  end

  #####################################
  # 特別休日登録処理
  #####################################
  def set_holiday
    date_holiday = params[:session][:date_holiday]

    # 整形が必要であればこれを使用する
    cal_Holiday = CalenderHoliday.find_by(date_holiday: date_holiday)

    # 指定日があるのなら
    if cal_Holiday
      # 指定日があるんでもう一度
      redirect_to '/tasks/specific_holiday_setting'
    else

      # 祝日判定
      if HolidayJp.holiday?(Date.parse(date_holiday))
        # 祝日フラグを1に
        holidayFlg = 1
      # そうでないなら
      else
        # 祝日フラグを0に
        holidayFlg = 0
      end

      # 特別休日の登録
      calender_holiday = CalenderHoliday.new(date_holiday: date_holiday, holiday_flg: holidayFlg)
      if calender_holiday
        calender_holiday.save
      end
      # 特別休日一覧に戻る
      redirect_to tasks_specific_holiday_setting_path
    end
  end

  #####################################
  # INFOMATION設定処理
  #####################################
  def set_information
    # パラメータの取得
    date_information = params[:session][:date_information]
    title = params[:session][:title]
    comment = params[:session][:comment]

      # INFOMATIONの登録
      information_setting = InformationSetting.new(date_information: date_information, title: title, comment: comment)
      if information_setting
        information_setting.save
      end
      # 一覧に戻る
      redirect_to tasks_information_setting_path
  end

  #####################################
  # ログインチェック
  #####################################
  def login_check
    # セッションに登録されていなければ
    if !session[:login]
      # ホームに戻る
      redirect_to root_path
    end
  end

  #####################################
  # 削除処理
  #####################################
  def destroy_calender_holiday
    # 削除対象の特別休日を取得
    delete_Cal =  CalenderHoliday.find(params[:id])

    # あるなら削除
    if delete_Cal
      delete_Cal.destroy
    end

    # 特別休日一覧に戻る
    redirect_to tasks_specific_holiday_setting_path
  end

  #####################################
  # 削除処理(information)
  #####################################
  def destroy_information
    # 削除対象の特別休日を取得
    information =  InformationSetting.find(params[:id])

    # あるなら削除
    if information
      information.destroy
    end

    # INFORMATION一覧に戻る
    redirect_to tasks_information_setting_path
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_logged_in.html.erb
<%= stylesheet_link_tag "tasks/logged_in", :media => "all" %>
<div class="mod-mainContent">
  <div class="wrapin wrapin-sp">
    <h1 class="logged_in_tasks_list_title">タスク一覧</h1>
    <table class="logged_in_tasks_list_table">
        <tbody>
          <tr class="logged_in_tasks_header text_center">
            <th>タスク名</th>
            <th>タスク内容</th>
          </tr>
          <tr data-link="<%= tasks_regular_holiday_setting_path %>" class="master_settings" >
              <td class="text_center">定休日設定</td>
              <td class="text_left">
                まり鍼灸院の定休日を設定することができます。<br>
                設定内容は、開院/定休日/午前休/午後休の4つを各曜日に対して設定することが出来ます。
              </td>
          </tr>
          <tr data-link="<%= tasks_specific_holiday_setting_path %>" class="master_settings">
            <td class="text_center">特別休日設定</td>
            <td class="text_left">
              まり鍼灸院の特別休日を設定することができます。<br>
              特別休日は、カレンダーより指定して休日を設定できます。
            </td>
          </tr>
          <tr data-link="<%= tasks_information_setting_path %>"  class="master_settings">
            <td class="text_center">INFOMATION設定</td>
            <td class="text_left">
              まり鍼灸院のINFOMATIONを設定することができます。<br>
              設定内容は日付、タイトル、本文となっており、指定された日付に、INFOMATIONを出すことが可能です。<br>
              ※日付を今日以前に指定した場合、即時反映となります。
            </td>
          </tr>
        </tbody>
    </table>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>

<%= javascript_include_tag 'tasks/tasks', 'data-turbolinks-track': 'reload' %>

app/views/tasks/_not_logged_in.html.erb
<p>タスクの管理ができるアプリです。まずはログインをしてください。</p>
<%= link_to "ログイン", login_path%>

app/views/tasks/index.html.erb
<h1>TODOアプリ</h1>
<% if logged_in? %>
  <%= render '/tasks/logged_in' %>
<% else %>
  <%= render '/tasks/not_logged_in' %>
<% end %>

app/views/tasks/information_setting.html.erb
<%= stylesheet_link_tag "tasks/information_setting", :media => "all" %>
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">

<div class="mod-mainContent">
  <div class="wrapin wrapin-sp">
    <%# 特別休日タイトル %>
    <h2 class="information_setting-h">
      <span class="ja">
        INFORMATION SETTING
      </span>
    </h2>
    <%# INFORMATION設定フォーム %>
    <div class="information_setting_input">
      <%= form_for(:session, url: tasks_information_setting_path) do |f| %>
        <div class="mod-form">
          <table class="mod-form-table">
            <tbody>
              <tr>
                <th>表示させる日付<span class="must">※必須</span></th>
                <td>
                  <%= f.date_field :date_information , :class => 'u-input size-100p', :size => '60', :id => 'date_information', :placeholder => "例：2020/11/07", :required => true, autocomplete: 'off' %>
                </td>
              </tr>
              <tr>
                <th>タイトル<span class="must">※必須</span></th>
                <td>
                  <%= f.text_field :title, :class => 'u-input size-100p', :size => '60', :placeholder => "例：ホームページ開設しました", :required => true, autocomplete: 'off' %>
                </td>
              </tr>
              <tr>
                <th>内容<span class="must">※必須</span></th>
                <td>
                  <%= f.text_area :comment, :class => 'u-input size-100p', :cols => '50', :rows => '10', :required => true %>
                </td>
              </tr>
            </tbody>
          </table>
          <div class="mod-form-btns">
            <div class="mod-btns1col u-mb-1e">
              <div class="mod-btns1col-item"></div>
            </div>
            <div class="mod-btns1col">
              <div class="mod-btns1col-item">
                <%= f.submit '登録', class: 'btn btn-primary mod-btn01 u-bg-c1 u-c-wh', data: { confirm: "登録してもいいですか？"} %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <%# INFORMATION SETTING一覧表示タイトル %>
    <h2 class="information_setting-h">
      <span class="ja">
        INFORMATION SETTING一覧
      </span>
    </h2>
    <%# 特別休日一覧表示 %>
    <div class="specific_holiday_setting_input">
      <table class="specifics_table">
        <tbody>
            <tr class="specifics_title">
                <th>date_information</th>
                <th>title</th>
                <th>comment</th>
                <th></th>
            </tr>
            <% @informationSetting.each do |information| %>
            <tr class="specifics_content">
              <td><%= information.date_information %></td>
              <td><%= information.title %></td>
              <td><%= information.comment %></td>
              <td class="information_setting_delete">
                <%= link_to('削除',tasks_information_setting_path(:id => information.id),
                                method: :delete,data: {confirm:'削除してもいいですか？'}, class: "delete_btn mod-btn02 u-c-wh")%>
              </td>
            </tr>
            <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1/i18n/jquery.ui.datepicker-ja.min.js"></script>
<script>
	$(function() {
		$.datepicker.setDefaults($.datepicker.regional["ja"]);
		$("#date_information").datepicker();
	});
</script>

app/views/tasks/regular_holiday_setting.html.erb
<%= stylesheet_link_tag "tasks/regular_holiday_setting", :media => "all" %>
<script type="module">
  import "regular_holiday_setting";
  import "tasks";
</script>
<div class="mod-mainContent">
  <div class="wrapin wrapin-sp">
    <h2 class="regular_holiday_setting-h">
      <span class="ja">
        SCHEDULE
      </span>
    </h2>
    <section class="home-schedule">
      <div class="home-schedule-head">
        <h2 class="home-info-h">変更したい定休日を選択してください。変更した内容で問題ないようでしたら登録を押してください。</h2>
      </div>
      <table class="mod-schedule-table">
        <tbody>
          <tr>
            <th></th>
            <th>月</th>
            <th>火</th>
            <th>水</th>
            <th>木</th>
            <th>金</th>
            <th>土</th>
            <th>日</th>
          </tr>
          <tr>
            <td class="tal">9:30 - 13:00</td>
            <% if @calenderHolidaySchedule[:monday] == 1 or @calenderHolidaySchedule[:monday] == 3 then %>
              <td class="open" id="am_Mon">〇</td>
              <% am_Mon = 1 %>
            <% else %>
              <td class="close" id="am_Mon">ー</td>
              <% am_Mon = 0 %>
            <% end %>
            <% if @calenderHolidaySchedule[:tuesday] == 1 or @calenderHolidaySchedule[:tuesday] == 3 then %>
              <td class="open" id="am_Tue">〇</td>
              <% am_Tue = 1 %>
            <% else %>
              <td class="close" id="am_Tue">ー</td>
              <% am_Tue = 0 %>
            <% end %>
            <% if @calenderHolidaySchedule[:wednesday] == 1 or @calenderHolidaySchedule[:wednesday] == 3 then %>
              <td class="open" id="am_Wed">〇</td>
              <% am_Wed = 1 %>
            <% else %>
              <td class="close" id="am_Wed">ー</td>
              <% am_Wed = 0 %>
            <% end %>
            <% if @calenderHolidaySchedule[:thursday] == 1 or @calenderHolidaySchedule[:thursday] == 3 then %>
              <td class="open" id="am_Thu">〇</td>
              <% am_Thu = 1 %>
            <% else %>
              <td class="close" id="am_Thu">ー</td>
              <% am_Thu = 0 %>
            <% end %>
            <% if @calenderHolidaySchedule[:friday] == 1 or @calenderHolidaySchedule[:friday] == 3 then %>
              <td class="open" id="am_Fri">〇</td>
              <% am_Fri = 1 %>
            <% else %>
              <td class="close" id="am_Fri">ー</td>
              <% am_Fri = 0 %>
            <% end %>
            <% if @calenderHolidaySchedule[:saturday] == 1 or @calenderHolidaySchedule[:saturday] == 3 then %>
              <td class="open" id="am_Sat">〇</td>
              <% am_Sat = 1 %>
            <% else %>
              <td class="close" id="am_Sat">ー</td>
              <% am_Sat = 0 %>
            <% end %>
            <% if @calenderHolidaySchedule[:sunday] == 1 or @calenderHolidaySchedule[:sunday] == 3 then %>
              <td class="open" id="am_Sun">〇</td>
              <% am_Sun = 1 %>
            <% else %>
              <td class="close" id="am_Sun">ー</td>
              <% am_Sun = 0 %>
            <% end %>
          </tr>
          <tr>
            <td class="tal">14:30 - 19:00</td>
            <% if @calenderHolidaySchedule[:monday] == 2 or @calenderHolidaySchedule[:monday] == 3 then %>
              <td class="open" id="pm_Mon">〇</td>
              <% pm_Mon = 2 %>
            <% else %>
              <td class="close" id="pm_Mon">ー</td>
              <% pm_Mon = 0 %>
            <% end %>
            <% if @calenderHolidaySchedule[:tuesday] == 2 or @calenderHolidaySchedule[:tuesday] == 3 then %>
              <td class="open" id="pm_Tue">〇</td>
              <% pm_Tue = 2 %>
            <% else %>
              <td class="close" id="pm_Tue">ー</td>
              <% pm_Tue = 0 %>
            <% end %>
            <% if @calenderHolidaySchedule[:wednesday] == 2 or @calenderHolidaySchedule[:wednesday] == 3 then %>
              <td class="open" id="pm_Wed">〇</td>
              <% pm_Wed = 2 %>
            <% else %>
              <td  class="close" id="pm_Wed">ー</td>
              <% pm_Wed = 0 %>
            <% end %>
            <% if @calenderHolidaySchedule[:thursday] == 2 or @calenderHolidaySchedule[:thursday] == 3 then %>
              <td class="open" id="pm_Thu">〇</td>
              <% pm_Thu = 2 %>
            <% else %>
              <td class="close" id="pm_Thu">ー</td>
              <% pm_Thu = 0 %>
            <% end %>
            <% if @calenderHolidaySchedule[:friday] == 2 or @calenderHolidaySchedule[:friday] == 3 then %>
              <td class="open" id="pm_Fri">〇</td>
              <% pm_Fri = 2 %>
            <% else %>
              <td class="close" id="pm_Fri">ー</td>
              <% pm_Fri = 0 %>
            <% end %>
            <% if @calenderHolidaySchedule[:saturday] == 2 or @calenderHolidaySchedule[:saturday] == 3 then %>
              <td class="open" id="pm_Sat">〇</td>
              <% pm_Sat = 2 %>
            <% else %>
              <td class="close" id="pm_Sat">ー</td>
              <% pm_Sat = 0 %>
            <% end %>
            <% if @calenderHolidaySchedule[:sunday] == 2 or @calenderHolidaySchedule[:sunday] == 3 then %>
              <td class="open" id="pm_Sun">〇</td>
              <% pm_Sun = 2 %>
            <% else %>
              <td class="close" id="pm_Sun">ー</td>
              <% pm_Sun = 0 %>
            <% end %>
          </tr>
        </tbody>
      </table>
      <p class="mod-schedule-notes">
        ※ ー は定休（祝日は不定休）
      </p>
    </section>
    <div class="regular_holiday_setting_input">
      <%= form_for(:session, url: tasks_regular_holiday_setting_path) do |f| %>
        <div class="mod-form">
          <%= f.hidden_field :am_Mon, :value => am_Mon %>
          <%= f.hidden_field :am_Tue, :value => am_Tue %>
          <%= f.hidden_field :am_Wed, :value => am_Wed %>
          <%= f.hidden_field :am_Thu, :value => am_Thu %>
          <%= f.hidden_field :am_Fri, :value => am_Fri %>
          <%= f.hidden_field :am_Sat, :value => am_Sat %>
          <%= f.hidden_field :am_Sun, :value => am_Sun %>
          <%= f.hidden_field :pm_Mon, :value => pm_Mon %>
          <%= f.hidden_field :pm_Tue, :value => pm_Tue %>
          <%= f.hidden_field :pm_Wed, :value => pm_Wed %>
          <%= f.hidden_field :pm_Thu, :value => pm_Thu %>
          <%= f.hidden_field :pm_Fri, :value => pm_Fri %>
          <%= f.hidden_field :pm_Sat, :value => pm_Sat %>
          <%= f.hidden_field :pm_Sun, :value => pm_Sun %>
          <div class="mod-form-btns">
            <div class="mod-btns1col u-mb-1e">
              <div class="mod-btns1col-item"></div>
            </div>
            <div class="mod-btns1col">
              <div class="mod-btns1col-item">
                <%= f.submit '登録', class: 'btn btn-primary mod-btn01 u-bg-c1 u-c-wh' %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
  </div>
</div>

<%= javascript_include_tag 'tasks/regular_holiday_setting', 'data-turbolinks-track': 'reload' %>

app/views/tasks/specific_holiday_setting.html.erb
<%= stylesheet_link_tag "tasks/specific_holiday_setting", :media => "all" %>
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">

<div class="mod-mainContent">
  <div class="wrapin wrapin-sp">
    <%# 特別休日タイトル %>
    <h2 class="specific_holiday_setting-h">
      <span class="ja">
        特別休日
      </span>
    </h2>
    <%# 特別休日指定フォーム %>
    <div class="specific_holiday_setting_input">
      <%= form_for(:session, url: tasks_specific_holiday_setting_path) do |f| %>
        <div class="mod-form">
          <table class="mod-form-table">
            <tbody>
              <tr>
                <th>特別休日指定</th>
                <td>
                  <%= f.date_field :date_holiday , :class => 'u-input size-100p', :size => '60', :id => 'specific_holiday', :placeholder => "例：2020/11/07", :required => true, autocomplete: 'off' %>
                </td>
              </tr>
            </tbody>
          </table>
          <div class="mod-form-btns">
            <div class="mod-btns1col u-mb-1e">
              <div class="mod-btns1col-item"></div>
            </div>
            <div class="mod-btns1col">
              <div class="mod-btns1col-item">
                <%= f.submit '登録', class: 'btn btn-primary mod-btn01 u-bg-c1 u-c-wh' %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <%# 特別休日一覧表示タイトル %>
    <h2 class="specific_holiday_setting-h">
      <span class="ja">
        特別休日一覧
      </span>
    </h2>
    <%# 特別休日一覧表示 %>
    <div class="specific_holiday_setting_input">
      <table class="specifics_table">
        <tbody>
            <tr class="specifics_title">
                <th>特別休日</th>
                <th></th>
            </tr>
            <% @calenderHolidays.each do |calenderHoliday| %>
            <tr class="specifics_content">
              <td><%= calenderHoliday.date_holiday %></td>
              <td>
                <%= link_to('削除',tasks_specific_holiday_setting_path(:id => calenderHoliday.id),
                                method: :delete,data: {confirm:'削除してもいいですか？'}, class: "delete_btn mod-btn02 u-c-wh")%>
              </td>
            </tr>
            <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1/i18n/jquery.ui.datepicker-ja.min.js"></script>
<script>
	$(function() {
		$.datepicker.setDefaults($.datepicker.regional["ja"]);
		$("#specific_holiday").datepicker();
	});
</script>