config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # ホーム画面(最初にアクセスしたときのビューの指定)
  root 'home#index'                                                                         # ホーム画面

  # はじめての方へ #
  get '/beginner',                                  to: 'beginner#index'                    # 鍼灸治療とは
  get '/beginner/visit',                            to: 'beginner#visit'                    # ご来院にあたって
  get '/beginner/self-introduction',                to: 'beginner#self-introduction'        # 施術者紹介

  # 施術の流れ #
  get '/procedure_flow',                            to: 'procedure_flow#index'              # 施術の流れ

  # 治療方針 #
  get '/treatment_policy',                          to: 'treatment_policy#index'            # 治療方針
  get '/treatment_policy/faq',                      to: 'treatment_policy#faq'              # こんな症状にお悩みなら
  get '/treatment_policy/lifestyle',                to: 'treatment_policy#lifestyle'        # ライフスタイルに合わせた治療方針
  get '/treatment_policy/reverberation',            to: 'treatment_policy#reverberation'    # 痛い鍼はヘタなのか

  # お問い合わせ #
  get   '/contact',                                 to: 'contact#index'                     # お問い合わせ
  get   '/contact/confirm',                         to: 'contact#index'                     # お問い合わせ
  post  '/contact/confirm',                         to: 'contact#confirm'                   # 確認画面
  get   '/contact/thanks',                          to: 'home#index'                        # ホーム画面
  post  '/contact/thanks',                          to: 'contact#thanks'                    # 送信完了

  # ログイン系 #
  get     '/login',                                 to: 'sessions#new'
  post    '/login',                                 to: 'sessions#create'
  delete  '/logout',                                to: 'sessions#destroy'

  # その他 #
  get '/other/calender',                            to: 'other#calender'                    # カレンダー一覧

  # 管理者用 #
  get     '/tasks',                                 to: 'tasks#index'                       # 管理者ページログイン画面
  get     '/tasks/logged_in',                       to: 'tasks#_logged_in'                  # ログイン成功(設定画面へ)
  get     '/tasks/not_logged_in',                   to: 'tasks#_not_logged_in'              # ログイン失敗(ログイン画面へ)
  get     '/tasks/regular_holiday_setting',         to: 'tasks#regular_holiday_setting'     # 定休日設定
  post    '/tasks/regular_holiday_setting',         to: 'tasks#set_regular_holiday'         # 定休日設定(データ登録処理)
  get     '/tasks/specific_holiday_setting',        to: 'tasks#specific_holiday_setting'    # 特別休日設定
  post    '/tasks/specific_holiday_setting',        to: 'tasks#set_holiday'                 # 特別休日設定(データ登録処理)
  delete  '/tasks/specific_holiday_setting',        to: 'tasks#destroy_calender_holiday'    # 特別休日設定(データ消去処理)
  get     '/tasks/information_setting',             to: 'tasks#information_setting'         # INFORMATION設定
  post    '/tasks/information_setting',             to: 'tasks#set_information'             # INFORMATION設定(データ登録処理)
  delete  '/tasks/information_setting',             to: 'tasks#destroy_information'         # INFORMATION設定(データ消去処理)

  # 404/500系エラー対応 #
  # ★★★これは一番下に設定しないとおかしなことになるよ！！★★★
  #get '*not_found' => 'application#routing_error'
  #post '*not_found' => 'application#routing_error'
  # ★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★

end

app/controllers/treatment_policy_controller.rb
class TreatmentPolicyController < ApplicationController
  # 治療方針
  def index
  end

  # こんな症状にお悩みなら
  def faq
    # オープンさせるfaqがあれば値が入ってくる
    @faqID = params[:faq_id];
  end

  # ライフスタイルに合わせた治療方針
  def lifestyle
  end

  # 痛い鍼はヘタなのか
  def reverberation
  end
end

app/helpers/treatment_policy_helper.rb
module TreatmentPolicyHelper
end

app/views/treatment_policy/index.html.erb
<%= stylesheet_link_tag "treatment_policy/treatment_policy", :media => "all" %>
<%# 画面上部イメージ %>
<div class="mod-keyvisualHead align-lb u-c-wh">
  <h1 class="mod-keyvisualHead-txts">
    手から伝える一人ひとりへの思い
  </h1>
</div>
<%# パンくずリスト %>
<nav class="mod-breadcrumb">
  <ol class="mod-breadcrumb-links lapctbOnly">
    <li><%= link_to "まり鍼灸院", root_path, data: {"turbolinks" => false} %></li>
    <li>治療方針</li>
  </ol>
</nav>
<%# メインコンテンツ %>
<div class="mod-mainContent">
  <div class="treatment_policy wrapin">
    <h2 class="treatment_policy-h">
      <span class="ja">
        「淺野式」の治療方法をもとに実践しています。
      </span>
    </h2>
    <div class="treatment_policy-content">
      淺野周先生が考案された<span class="u-c-c1">「淺野式」</span>は主に痛みの治療を得意としており、<br>
      <span class="u-c-c1">「広範囲に痛みを出しているのは骨付近にある太い神経が圧迫されているから」</span>という仮説のもと骨表面や深部の筋肉を緩めることで、<br>
      神経や血管への圧迫がなくなり、筋肉に血液が循環するようになり、その結果痛みが解消し治癒すると考え、鍼治療を行っています。<br>
      <br>
      筋肉が原因となって出現する頑固な痛みやコリはなぜ起こり、なぜ多くの場合慢性化してしまうのでしょうか。<br>
      それは、<span class="u-c-c1">オーバーユーズ</span>（使いすぎ）や<span class="u-c-c1">ストレス</span>、<span class="u-c-c1">筋肉に負担のかかる姿勢を長く続けている</span>（長時間のパソコン作業等）など、痛みのきっかけはいろいろあると思います。<br>
      そしてその状況が長く続くほど、筋肉は固くなります。<br>
      <span class="u-c-c1">硬くなった筋肉は血管を圧迫するため、血流が悪くなります。</span><br>
      血流が悪くなれば筋肉に酸素や栄養素が十分に届かないばかりか、疲労物質や痛みのもとになる発痛物質を流すことができなくなり、その結果さらに筋肉は硬くなります。<br>
      この悪循環がつらい症状を長引かせてしまうのです。<br>
      <br>
      そして、この<span class="u-c-c1">悪循環を断ち切るのが、鍼治療</span>です。<br>
      鍼治療では表面の筋肉だけでなく、手などでは直接触ることのできない、深いところにある筋肉（インナーマッスル）にまで直接アプローチすることができます。<br>
      硬くなった筋肉に直接鍼をすることで、筋肉がゆるみ血流が回復し、痛みを取り除きます。<br>
      <br>
      また、直接手で触れるような表面の筋肉、つまり皆さんがつらくてよく手で触ったり、もんだりしている場所の筋肉の緊張をだけを治療しても、症状が改善しなかったり、すぐにもとのつらさに戻ってしまうのはなぜでしょうか？<br>
      それは、身体の深いところの筋肉が硬くなり神経を圧迫することで、表面の筋肉が硬くなっているからです。<br>
      つまり深い場所の筋肉を緩め、神経の圧迫をとってあげなければ、表面の筋肉は緩まないのです。<br>
      <br>
      そこで<span class="u-c-c1">「淺野式」</span>鍼治療の出番です。<br>
      浅い筋肉にしか鍼を刺さない治療院が多い中、<span class="u-c-c1">「淺野式」</span>では深い場所の筋肉まで鍼を到達させることができます。<br>
      そうすることで、神経は圧迫から解放され、筋肉の血流も回復し、頑固な痛みやコリを解消できます。
    </div>
    <section class="treatment_policy-difference">
      <div class="treatment_policy-difference-bluelite dsp-flx">
        <div class="treatment_policy-difference-img left-side">
          <%= image_tag 'beginner/beginner_answer_image_01.jpg' %>
          <p class="treatment_policy-difference-cat">淺野式治療</p>
        </div>
        <div class="treatment_policy-difference-contents">
          淺野周先生の治療方法を忠実に行っている。<br>
          <br>
          鍼の本数６０本以上、置鍼時間が４０分程度。<br>
          鍼の深さが骨にまで達する。
        </div>
      </div>
      <div class="treatment_policy-difference-blue dsp-flx">
        <div class="treatment_policy-difference-img right-side">
          <%= image_tag 'beginner/beginner_answer_image_02.jpg' %>
          <p class="treatment_policy-difference-cat">北京堂式治療</p>
        </div>
        <div class="treatment_policy-difference-contents">
          治療の一部に北京堂の治療方法を取り入れていいる。<br>
          <br>
          鍼の本数が少なく、置鍼時間も短い。<br>
          鍼の深さが浅野式と比べて浅い。
        </div>
      </div>
    </section>
  </div>
</div>

app/views/treatment_policy/lifestyle.html.erb
<%= stylesheet_link_tag "treatment_policy/lifestyle", :media => "all" %>
<%# 画面上部イメージ %>
<div class="mod-catHead01">
  <h1 class="mod-catHead01-h">
    ライフスタイルに合わせた治療方針
  </h1>
</div>
<%# パンくずリスト %>
<nav class="mod-breadcrumb">
  <ol class="mod-breadcrumb-links lapctbOnly">
    <li><%= link_to "まり鍼灸院", root_path, data: {"turbolinks" => false} %></li>
    <li><%= link_to "治療方針", treatment_policy_path, data: {"turbolinks" => false} %></li>
    <li>ライフスタイルに合わせた治療方針</li>
  </ol>
</nav>
<%# ライフスタイルに合わせた治療方針リスト %>
<section class="mod-sec01">
  <div class="wrapin wrapin-sp">
    <div class="cat">
      <%# 社会人の方へ %>
      <section class="treatment_policy-lifestyle-sec" id="lifestyle01">
        <div class="treatment_policy-lifestyle-q">
          <div class="treatment_policy-lifestyle-q-col">
            <p class="treatment_policy-lifestyle-q-h">
              社会人の方へ
            </p>
          </div>
          <div class="treatment_policy-lifestyle-q-btn" data-name="＋"></div>
        </div>
        <div class="treatment_policy-lifestyle-q-a">
          <div class="treatment_policy-lifestyle-q-a-claer">
            <div class="treatment_policy-lifestyle-q-a-cat u-bd-c1">
              方針
            </div>
            <div class="treatment_policy-lifestyle-q-a-txts">
              <p>
                ● 心身ともにリラックス<br>
                過労やストレスにより乱れた自律神経のバランスを調整し、心と体にリラックス作用を与えます。<br>
                なんとなく体調がすぐれない、という方もお試しください。<br>
                <br>
                ● こんな方におすすめ<br>
                ・パソコン仕事などの眼精疲労　・片頭痛　・うつ病　・生活習慣病<br>
                <br>
                ● 生活習慣病の改善へ<br>
                鍼灸マッサージだけでなく、毎日の食生活にかかせない食生活の指導とそれを補うサプリメントで生活習慣病の予防や改善に効果的です。<br>
                <br>
              </p>
              <div class="treatment_policy-lifestyle-q-a-closeBtn">
                <p class="mod-btn01 u-bd-c1 u-c-c1">
                  閉じる
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
      <%# 中高年の方へ %>
      <section class="treatment_policy-lifestyle-sec" id="lifestyle01">
        <div class="treatment_policy-lifestyle-q">
          <div class="treatment_policy-lifestyle-q-col">
            <p class="treatment_policy-lifestyle-q-h">
              中高年の方へ
            </p>
          </div>
          <div class="treatment_policy-lifestyle-q-btn" data-name="＋"></div>
        </div>
        <div class="treatment_policy-lifestyle-q-a">
          <div class="treatment_policy-lifestyle-q-a-claer">
            <div class="treatment_policy-lifestyle-q-a-cat u-bd-c1">
              方針
            </div>
            <div class="treatment_policy-lifestyle-q-a-txts">
              <p>
                ● 健康維持、リハビリに最適<br>
                年齢とともに感じる関節の痛みや神経痛等、不快な症状の緩和のほか、
                各種障害に対するリハビリテーションとして、健康づくりのお手伝いをいたします。<br>
                <br>
                ● こんな方におすすめ<br>
                ・体調のすぐれない方　・更年期障害　・線維筋痛症<br>
                はり・きゅう・マッサージで改善へ<br>
                <br>
              </p>
              <div class="treatment_policy-lifestyle-q-a-closeBtn">
                <p class="mod-btn01 u-bd-c1 u-c-c1">
                  閉じる
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
      <%# 男性の方へ %>
      <section class="treatment_policy-lifestyle-sec" id="lifestyle01">
        <div class="treatment_policy-lifestyle-q">
          <div class="treatment_policy-lifestyle-q-col">
            <p class="treatment_policy-lifestyle-q-h">
              男性の方へ
            </p>
          </div>
          <div class="treatment_policy-lifestyle-q-btn" data-name="＋"></div>
        </div>
        <div class="treatment_policy-lifestyle-q-a">
          <div class="treatment_policy-lifestyle-q-a-claer">
            <div class="treatment_policy-lifestyle-q-a-cat u-bd-c1">
              方針
            </div>
            <div class="treatment_policy-lifestyle-q-a-txts">
              <p>
                ● こんな方におすすめ<br>
                ・メタボリック　・お仕事の疲れ<br>
                <br>
                お仕事を頑張っているお父さん、お疲れの方の心と体のケアとリフレッシュに最適です。<br>
                <br>
              </p>
              <div class="treatment_policy-lifestyle-q-a-closeBtn">
                <p class="mod-btn01 u-bd-c1 u-c-c1">
                  閉じる
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
      <%# 女性の方へ %>
      <section class="treatment_policy-lifestyle-sec" id="lifestyle01">
        <div class="treatment_policy-lifestyle-q">
          <div class="treatment_policy-lifestyle-q-col">
            <p class="treatment_policy-lifestyle-q-h">
              女性の方へ
            </p>
          </div>
          <div class="treatment_policy-lifestyle-q-btn" data-name="＋"></div>
        </div>
        <div class="treatment_policy-lifestyle-q-a">
          <div class="treatment_policy-lifestyle-q-a-claer">
            <div class="treatment_policy-lifestyle-q-a-cat u-bd-c1">
              方針
            </div>
            <div class="treatment_policy-lifestyle-q-a-txts">
              <p>
                ● こんな方におすすめ<br>
                ・更年期障害　・生理痛　・冷え症　・線維筋痛症<br>
                ・生活習慣病（高血圧、糖尿病など）<br>
                ・不妊、逆子　・メニエール　・自律神経<br>
                <br>
                鍼灸により血流循環、気の流れ、自律神経のバランス、体質改善、
                免疫力・自然治癒力を高める作用がありますので、女性特有の症状にも効果的です。<br>
                <br>
                ● 妊婦さんや産後のお母さんへ<br>
                産前産後の健康管理、流産、逆子の予防、母子ともに健康でいるための手助けにはり・灸は最適です。
                また産後の体力回復にも最適です。なかなか子宝に恵まれない、不妊でお悩みの方もご相談下さい。<br>
                <br>
              </p>
              <div class="treatment_policy-lifestyle-q-a-closeBtn">
                <p class="mod-btn01 u-bd-c1 u-c-c1">
                  閉じる
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
      <%# 小、中、高生へ %>
      <section class="treatment_policy-lifestyle-sec" id="lifestyle01">
        <div class="treatment_policy-lifestyle-q">
          <div class="treatment_policy-lifestyle-q-col">
            <p class="treatment_policy-lifestyle-q-h">
              小、中、高生へ
            </p>
          </div>
          <div class="treatment_policy-lifestyle-q-btn" data-name="＋"></div>
        </div>
        <div class="treatment_policy-lifestyle-q-a">
          <div class="treatment_policy-lifestyle-q-a-claer">
            <div class="treatment_policy-lifestyle-q-a-cat u-bd-c1">
              方針
            </div>
            <div class="treatment_policy-lifestyle-q-a-txts">
              <p>
                ● 集中力・記憶力のアップへ<br>
                小・中・高生または受験生の方で、勉強しても思うように成果が上がらない方、勉強でお悩みの方におすすめです。
                はり・きゅうにより集中力や記憶力のアップに効果があります。<br>
                <br>
              </p>
              <div class="treatment_policy-lifestyle-q-a-closeBtn">
                <p class="mod-btn01 u-bd-c1 u-c-c1">
                  閉じる
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
      <%# お子様へ %>
      <section class="treatment_policy-lifestyle-sec" id="lifestyle01">
        <div class="treatment_policy-lifestyle-q">
          <div class="treatment_policy-lifestyle-q-col">
            <p class="treatment_policy-lifestyle-q-h">
              お子様へ
            </p>
          </div>
          <div class="treatment_policy-lifestyle-q-btn" data-name="＋"></div>
        </div>
        <div class="treatment_policy-lifestyle-q-a">
          <div class="treatment_policy-lifestyle-q-a-claer">
            <div class="treatment_policy-lifestyle-q-a-cat u-bd-c1">
              方針
            </div>
            <div class="treatment_policy-lifestyle-q-a-txts">
              <p>
                ● 小さなお子様でも安心して受けられる小児はり治療<br>
                子供用の刺さないはりで皮膚を撫でたりツボを刺激し、子供が本来持っている治癒力を高めます。
                夜鳴き、かんの虫等、お子様のことでお悩みの方のご相談にお答えします。<br>
                <br>
              </p>
              <div class="treatment_policy-lifestyle-q-a-closeBtn">
                <p class="mod-btn01 u-bd-c1 u-c-c1">
                  閉じる
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
      <%# スポーツをしている方へ %>
      <section class="treatment_policy-lifestyle-sec" id="lifestyle01">
        <div class="treatment_policy-lifestyle-q">
          <div class="treatment_policy-lifestyle-q-col">
            <p class="treatment_policy-lifestyle-q-h">
              スポーツをしている方へ
            </p>
          </div>
          <div class="treatment_policy-lifestyle-q-btn" data-name="＋"></div>
        </div>
        <div class="treatment_policy-lifestyle-q-a">
          <div class="treatment_policy-lifestyle-q-a-claer">
            <div class="treatment_policy-lifestyle-q-a-cat u-bd-c1">
              方針
            </div>
            <div class="treatment_policy-lifestyle-q-a-txts">
              <p>
                ● 試合前の調整・スポーツ障害に<br>
                ケガの予防や、試合前のコンディショニング（調整）に最適です。<br>
                学生さんや、ママさんチームの方のご利用も多数あります。<br>
                <br>
              </p>
              <div class="treatment_policy-lifestyle-q-a-closeBtn">
                <p class="mod-btn01 u-bd-c1 u-c-c1">
                  閉じる
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
</section>
<input type="hidden" id="faqId" name="hidden_faqId" value=<%= @faqID %>>
<%= javascript_include_tag 'treatment_policy/treatment_policy', 'data-turbolinks-track': 'reload' %>

app/views/treatment_policy/reverberation.html.erb
<%= stylesheet_link_tag "treatment_policy/reverberation", :media => "all" %>
<%# 画面上部イメージ %>
<div class="mod-keyvisualHead align-lb u-c-wh">
  <h1 class="mod-keyvisualHead-txts">
    治りたい、身体のチカラをサポートします。
  </h1>
</div>
<%# パンくずリスト %>
<nav class="mod-breadcrumb">
  <ol class="mod-breadcrumb-links lapctbOnly">
    <li><%= link_to "まり鍼灸院", root_path, data: {"turbolinks" => false} %></li>
    <li><%= link_to "治療方針", treatment_policy_path, data: {"turbolinks" => false} %></li>
    <li>痛い鍼はヘタなのか</li>
  </ol>
</nav>
<%# メインコンテンツ %>
<div class="mod-mainContent">
  <div class="treatment_policy-reverberation wrapin wrapin-sp">
    <h2 class="treatment_policy-reverberation-h">
      <span class="ja">
        響き（痛み）についてのよくある誤解
      </span>
    </h2>
    <div class="treatment_policy-reverberation-content">
      <div class="treatment_policy-reverberation-space"></div>
      <div class="treatment_policy-reverberation-img-right">
        <%= image_tag 'treatment_policy/treatment_policy_reverberation_01.jpg' %>
      </div>
      <div class="treatment_policy-reverberation-space2"></div>
      <div class="treatment_policy-reverberation-img-left">
        <%= image_tag 'treatment_policy/treatment_policy_reverberation_02.jpg' %>
      </div>
      <p class="treatment_policy-reverberation-content-txt">
        鍼治療で、痛い鍼はヘタで痛くない鍼が上手なのだ！という噂があります。<br>
        実はこれ、<span class="u-c-c1">半分正解で半分は見当違い</span>なのです。<br>
        <br>
        当治療院の針はズーンという響きのある治療を行います。患者様によってはこの響きを「痛い」と表現されます。<br>
        <br>
        鍼を打つ時には、当然ながら最初に刺さるのは皮膚です。<br>
        技量が未熟だと、この皮膚を突破するときに「チクッ」という痛みが生じます。<br>
        これを切皮痛（せっぴつう）といって、こういう
        <span class="u-c-c1">「痛み」を随所に感じる場合残念ながらヘタな鍼灸師</span>なので、早急に治療院を変えたほうがいいです。<br>
        <br>
        ところが、切皮痛はないけれども<br>
        <span class="u-c-c1">刺した後で、ズシンと響く「痛み」</span>があります。<br>
        これは逆にどれだけきちんと響きを出せるか？ということが重要なので<br>
        当院のような深い鍼灸治療を行う場合は、この「痛み」がないとヘタということになります。<br>
        <br>
        つまり「痛い鍼はヘタで痛くない鍼が上手なのだ！」という理屈は<span class="u-c-c1">認識の違い</span>ということなのです。<br>
        <br>
        これを混同してしまうと<br>
        <br>
        患者さんが、友人に当医院の治療で改善したことを話したときに<br>
        「痛い鍼はヘタなんだから、行くのをやめたほうがいい」と言われたり<br>
        <br>
        別の鍼灸院で<br>
        「痛い鍼はヘタなんですよ、うちは痛くないでしょう？」
        というような話を聞かされた、など不安になることがあります。<br>
        <br>
        前者は、切皮痛と響きを混同している「うわさ」ですし<br>
        <br>
        後者は、おそらく深く刺さない鍼治療を行っているのでしょう。<br>
        （その治療院が「痛くない鍼」できちんと治せているのでしたら当院のような「響く鍼」の治療にわざわざ通うことはないと思いますが・・・）<br>
        <br>
        <span class="u-c-c1">切皮痛と、響きをきちんと区別</span>できれば、それは話半分ということが理解できたのではないでしょうか？<br>
        理解できれば、そのような噂を気にすることはありません。<br>
        <br>
        当院ではきちんと痛みと響きを分けて認識していますし
        患者さんも、実際に<span class="u-c-c1">「痛み」と「響き」の違い</span>をキチンと体感して通院いただいています。
      </p>
    </div>
  </div>
</div>