config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # ホーム画面(最初にアクセスしたときのビューの指定)
  root 'home#index'                                                                         # ホーム画面

  # はじめての方へ #
  get '/beginner',                                  to: 'beginner#index'                    # 鍼灸治療とは
  get '/beginner/visit',                            to: 'beginner#visit'                    # ご来院にあたって
  get '/beginner/self-introduction',                to: 'beginner#self-introduction'        # 施術者紹介

  # 施術の流れ #
  get '/procedure_flow',                            to: 'procedure_flow#index'              # 施術の流れ

  # 治療方針 #
  get '/treatment_policy',                          to: 'treatment_policy#index'            # 治療方針
  get '/treatment_policy/faq',                      to: 'treatment_policy#faq'              # こんな症状にお悩みなら
  get '/treatment_policy/lifestyle',                to: 'treatment_policy#lifestyle'        # ライフスタイルに合わせた治療方針
  get '/treatment_policy/reverberation',            to: 'treatment_policy#reverberation'    # 痛い鍼はヘタなのか

  # お問い合わせ #
  get   '/contact',                                 to: 'contact#index'                     # お問い合わせ
  get   '/contact/confirm',                         to: 'contact#index'                     # お問い合わせ
  post  '/contact/confirm',                         to: 'contact#confirm'                   # 確認画面
  get   '/contact/thanks',                          to: 'home#index'                        # ホーム画面
  post  '/contact/thanks',                          to: 'contact#thanks'                    # 送信完了

  # ログイン系 #
  get     '/login',                                 to: 'sessions#new'
  post    '/login',                                 to: 'sessions#create'
  delete  '/logout',                                to: 'sessions#destroy'

  # その他 #
  get '/other/calender',                            to: 'other#calender'                    # カレンダー一覧

  # 管理者用 #
  get     '/tasks',                                 to: 'tasks#index'                       # 管理者ページログイン画面
  get     '/tasks/logged_in',                       to: 'tasks#_logged_in'                  # ログイン成功(設定画面へ)
  get     '/tasks/not_logged_in',                   to: 'tasks#_not_logged_in'              # ログイン失敗(ログイン画面へ)
  get     '/tasks/regular_holiday_setting',         to: 'tasks#regular_holiday_setting'     # 定休日設定
  post    '/tasks/regular_holiday_setting',         to: 'tasks#set_regular_holiday'         # 定休日設定(データ登録処理)
  get     '/tasks/specific_holiday_setting',        to: 'tasks#specific_holiday_setting'    # 特別休日設定
  post    '/tasks/specific_holiday_setting',        to: 'tasks#set_holiday'                 # 特別休日設定(データ登録処理)
  delete  '/tasks/specific_holiday_setting',        to: 'tasks#destroy_calender_holiday'    # 特別休日設定(データ消去処理)
  get     '/tasks/information_setting',             to: 'tasks#information_setting'         # INFORMATION設定
  post    '/tasks/information_setting',             to: 'tasks#set_information'             # INFORMATION設定(データ登録処理)
  delete  '/tasks/information_setting',             to: 'tasks#destroy_information'         # INFORMATION設定(データ消去処理)

  # 404/500系エラー対応 #
  # ★★★これは一番下に設定しないとおかしなことになるよ！！★★★
  #get '*not_found' => 'application#routing_error'
  #post '*not_found' => 'application#routing_error'
  # ★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★

end

app/models/contact.rb
class Contact < ApplicationRecord

  include ActiveModel::Model
  # メールアドレスチェック用正規表現
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  # 電話番号チェック用正規表現
  VALID_PHONE_REGEX = /\A\d{10}$|^\d{11}\z/

  attr_accessor :name, :email, :tel, :age, :comment

  # お名前の制限
  validates :name,    :presence =>  {:message => 'お名前を入力してください'}
  # emailの制限
  validates :email,   format: { with: VALID_EMAIL_REGEX,:message => 'メールアドレスの形式が正しくありません' }
  # 電話番号の制限
  validates :tel,     if: -> { !tel.blank? }, format: { with: VALID_PHONE_REGEX,:message => '電話番号はハイフンなしの半角数値で入力してください' }
  # ご相談内容の制限
  validates :comment, :presence =>  {:message => 'ご相談内容を入力してください'}
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  # 入力画面
  def index
    @contact = Contact.new
    render :action => 'index'
  end

  # 入力チェック
  def confirm
    # 入力値のチェック
    @contact = Contact.new(contact_params)
    respond_to do |format|
      # パラメータがある？
      if @contact.valid?
        # OK 確認画面を表示
        format.html { render :confirm, status: :unprocessable_entity }
      else
        # NG 入力画面を再表示
        format.html { render :index, status: :unprocessable_entity }
      end
    end
  end

  # ありがとう
  def thanks
    # 送信パラメータを設定
    @contact = Contact.new(contact_params)
    # メール送信
    ContactMailer.received_email(@contact).deliver
    respond_to do |format|
      # 完了画面を表示
      format.html { render :thanks, status: :unprocessable_entity }
    end
  end
private
  def contact_params
    params.require(:contact).permit(:name,:email, :tel, :age, :comment)
  end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/views/contact/confirm.html.erb
<%= stylesheet_link_tag "contact/contact_confirm", :media => "all" %>
<%# メインコンテンツ %>
<div class="mod-mainContent">
  <div class="wrapin wrapin-sp">
    <h2 class="contact-h">
      <span class="ja">
        お問い合わせ内容確認
      </span>
    </h2>
    <div class="mod-form">
      <%= form_for @contact, :url => contact_thanks_path do |f| %>
        <table class="mod-form-table">
          <tr>
            <th>お名前</th>
            <td>
              <%= f.hidden_field :name %>
              <div class="u-input size-100p">
                <%= simple_format(h(@contact.name)) %>
              </div>
            </td>
          </tr>
          <tr>
            <th>電話番号</th>
            <td>
              <%= f.hidden_field :tel %>
              <div class="u-input size-100p">
                <%= @contact.tel %>
              </div>
            </td>
          </tr>
          <tr>
            <th>メールアドレス</th>
            <td>
              <%= f.hidden_field :email %>
              <div class="u-input size-100p">
                <%= simple_format(h(@contact.email)) %>
              </div>
            </td>
          </tr>
          <tr>
            <th>ご年齢</th>
            <td>
              <%= f.hidden_field :age %>
              <div class="u-input size-100p">
                <%= @contact.age %>
              </div>
            </td>
          </tr>
          <tr>
            <th>ご相談内容</th>
            <td>
              <%= f.hidden_field :comment %>
              <div class="u-input size-100p">
                <%= simple_format(h(@contact.comment)) %>
              </div>
            </td>
          </tr>
        </table>
        <div class="mod-btns1col">
          <div class="mod-btns1col-item">
            <%= f.submit '送信', :class => 'btn btn-primary mod-btn01 u-bg-c1 u-c-wh' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/contact/index.html.erb
<%= stylesheet_link_tag "contact/contact", :media => "all" %>
<%# 画面上部イメージ %>
<div class="mod-keyvisualHead align-lb u-c-wh">
  <h1 class="mod-keyvisualHead-txts">
    お問い合わせ
  </h1>
</div>
<%# パンくずリスト %>
<nav class="mod-breadcrumb">
  <ol class="mod-breadcrumb-links lapctbOnly">
    <li><%= link_to "まり鍼灸院", root_path, data: {"turbolinks" => false} %></li>
    <li>お問い合わせ</li>
  </ol>
</nav>
<%# メインコンテンツ %>
<div class="mod-mainContent">
  <div class="wrapin wrapin-sp">
    <h2 class="contact-h">
      <span class="ja">
        当院へのご相談やお問い合わせについて
      </span>
    </h2>
    <%# お問い合わせフォーム %>
    <div class="contact_form_input">
      <%= form_with(model: @contact, url: contact_confirm_path) do |f| %>
        <div class="mod-form">
          <%# 入力エラー %>
          <% if @contact.errors.any? %>
          <div class="alert alert-danger" role="alert">
            <ul>
              <% @contact.errors.each do |attr, msg| %>
                <li class="u-c-rd wei-bold"><%= msg %></li>
              <% end %>
            </ul>
          </div>
          <% end %>
          <table class="mod-form-table">
            <tbody>
              <tr>
                <th>お名前<span class="must">※必須</span></th>
                <td>
                  <%= f.text_field :name, :class => 'u-input size-100p', :size => '60', :placeholder => "例：出雲 太郎", :required => true %>
                </td>
              </tr>
              <tr>
                <th>電話番号</th>
                <td>
                  <%= f.telephone_field :tel, :class => 'u-input size-100p', :size => '60', :inputmode =>'tel', :placeholder => "例：08012345678" %>
                </td>
              </tr>
              <tr>
                <th>メールアドレス<span class="must">※必須</span></th>
                <td>
                  <%= f.email_field :email, :class => 'u-input size-100p', :size => '60', :inputmode =>'email', :placeholder => "例：MariAcupuncture@example.com", :required => true %>
                </td>
              </tr>
              <tr>
                <th>ご年齢</th>
                <td>
                  <%= f.number_field :age, :class => 'u-input size-100p', :size => '60', :min => 1, :max => 100, :pattern =>'\d*', :placeholder => "例：40" %>
                </td>
              </tr>
              <tr>
                <th>ご相談内容<span class="must">※必須</span></th>
                <td>
                  <%= f.text_area :comment, :class => 'u-input size-100p', :cols => '50', :rows => '10', :required => true %>
                </td>
              </tr>
            </tbody>
          </table>
          <div class="mod-form-btns">
            <div class="mod-btns1col u-mb-1e">
              <div class="mod-btns1col-item"></div>
            </div>
            <div class="mod-btns1col">
              <div class="mod-btns1col-item">
                <%= f.submit '送信内容確認', class: 'btn btn-primary mod-btn01 u-bg-c1 u-c-wh' %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <%# お問い合わせフォームへ %>
  <section class="u-mb-2e">
    <div class="wrapin wrapin-sp">
      <div class="mod-contactLinks">
        <div class="mod-contactLinks-item is-tel">
          <a href="tel:080-xxxx-xxxx">
            <dl>
              <dt>
                <i><%= image_tag 'header/ico_tel_bu.svg' %></i>
                080-xxxx-xxxx
              </dt>
              <dd>お急ぎの場合はお電話で</dd>
            </dl>
          </a>
        </div>
        <div class="mod-contactLinks-item is-mail">
          <a href="/contact" data-turbolinks="false">
            <dl>
              <dt>メールによるご予約</dt>
              <dd>まずはお気軽にご連絡ください</dd>
            </dl>
          </a>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/contact/thanks.html.erb
<%= stylesheet_link_tag "contact/contact_thanks", :media => "all" %>
<%# メインコンテンツ %>
<div class="mod-mainContent">
  <div class="wrapin wrapin-sp">
    <h2 class="contact-h">
      <span class="ja">
        お問い合わせ
      </span>
    </h2>
    <div class="mod-thanks">
      お問い合わせいただきありがとうございました。
    </div>
  </div>
</div>